namespace JK.Common.PolyfillGenerators.Tests.Polyfills;

public class IsExternalInitPolyfillTests
{
    [Fact]
    public async Task Generates_IsExternalInit_Source()
    {
        CSharpSourceGeneratorTest<PolyfillGenerator, DefaultVerifier> context = new();

        // List of expected generated sources
        context.TestState.GeneratedSources
            .Add((typeof(PolyfillGenerator), "IsExternalInit.g.cs",
            """
            // <auto-generated/>
            #if !NET5_0_OR_GREATER

            using System.ComponentModel;
            using System.Diagnostics;
            using System.Diagnostics.CodeAnalysis;

            namespace System.Runtime.CompilerServices;

            [DebuggerNonUserCode]
            [ExcludeFromCodeCoverage]
            [EditorBrowsable(EditorBrowsableState.Never)]
            internal static class IsExternalInit
            {
            }

            #endif
            """));

        await context.RunAsync(TestContext.Current.CancellationToken);
    }
}
