namespace JK.Common.PolyfillGenerators.Polyfills;

internal struct IsExternalInitPolyfill : IGeneratedPolyfill
{
    public string FileName => IsExternalInitPolyfillStrings.FileName;

    public string SourceCode => IsExternalInitPolyfillStrings.SourceCode;
}

file static class IsExternalInitPolyfillStrings
{
    public const string FileName = "IsExternalInit";
    public const string SourceCode =
        """
        // <auto-generated/>
        #if !NET5_0_OR_GREATER

        using System.ComponentModel;
        using System.Diagnostics;
        using System.Diagnostics.CodeAnalysis;

        namespace System.Runtime.CompilerServices;

        [DebuggerNonUserCode]
        [ExcludeFromCodeCoverage]
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal static class IsExternalInit
        {
        }

        #endif
        """;
}
