namespace JK.Common.Generators.Polyfills;

internal static class IsExternalInitPolyfillFactory
{
    internal static Polyfill Create()
        => new()
        {
            FileName = "IsExternalInit",
            SourceCode = SourceCode,
        };

    public const string SourceCode =
        """
        // <auto-generated/>
        #if !NET5_0_OR_GREATER

        using System.ComponentModel;
        using System.Diagnostics;
        using System.Diagnostics.CodeAnalysis;

        namespace System.Runtime.CompilerServices;

        [DebuggerNonUserCode]
        [ExcludeFromCodeCoverage]
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal static class IsExternalInit
        {
        }

        #endif
        """;
}
