using System.Text;
using JK.Common.Data.Sql.BulkInsert.Attributes;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace JK.Common.Data.Sql.BulkInsert;

[Generator]
public sealed class BulkInsertGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<INamedTypeSymbol> classDeclaration = context.SyntaxProvider
            .ForAttributeWithMetadataName(typeof(BulkInsertableAttribute).FullName!,
                 predicate: static (s, _) => true,
                 transform: static (ctx, _) => GetSymbol(ctx));

        context.RegisterSourceOutput(classDeclaration,
            static (spc, source) => Execute(spc, source));
    }

    private static INamedTypeSymbol GetSymbol(GeneratorAttributeSyntaxContext ctx)
        => (INamedTypeSymbol)ctx.TargetSymbol;

    private static void Execute(SourceProductionContext context, INamedTypeSymbol typeSymbol)
    {
        try
        {
            var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : typeSymbol.ContainingNamespace.ToString();
            var name = typeSymbol.Name;
            var inserterClassName = $"{name}BulkInserter";
            var tableName = typeSymbol.GetTableName();
            PropertyMetadata[] props = typeSymbol.GetBulkInsertPropertyMetadata();

            var namespaceDeclaration = string.IsNullOrEmpty(ns)
                ? string.Empty
                : $"namespace {ns};";

            StringBuilder sb = new();
            sb.AppendLine(
                $$"""
                // <auto-generated />
                using System;
                using System.Collections.Generic;
                using System.Data;
                using System.Linq;
                using System.Reflection;
                using System.Text.RegularExpressions;
                using Microsoft.Data.SqlClient;

                {{namespaceDeclaration}}

                public static class {{inserterClassName}}
                {
                    public const string TableName = "{{tableName}}";

                    public static IDictionary<string, string> ColumnMappings => new Dictionary<string, string>
                    {
                """
            );

            // ColumnMappings
            for (var i = 0; i < props.Length; i++)
            {
                var comma = i < props.Length - 1 ? "," : "";
                sb.AppendIndentedLine(2, $"{{ \"{props[i].PropertyName}\", \"{props[i].ColumnName}\" }}{comma}");
            }

            sb.AppendLine(
                $$"""
                    };
                
                    public static void Execute(SqlConnection connection, IEnumerable<{{name}}> items, int batchSize = 0)
                    {
                        using (SqlBulkCopy bulk = new SqlBulkCopy(connection, SqlBulkCopyOptions.KeepNulls | SqlBulkCopyOptions.UseInternalTransaction, null))
                        {
                            if (connection.State != ConnectionState.Open)
                            {
                                connection.Open();
                            }
                
                            List<{{name}}> itemList = items.ToList();
                            bulk.BatchSize = batchSize == 0 ? itemList.Count : batchSize;
                            bulk.DestinationTableName = TableName;
                
                            foreach (KeyValuePair<string, string> mapping in ColumnMappings)
                            {
                                bulk.ColumnMappings.Add(mapping.Key, mapping.Value);
                            }
                
                            DataTable table = BuildDataTable(itemList);
                            try
                            {
                                bulk.WriteToServer(table);
                            }
                            catch (SqlException ex)
                            {
                                ThrowIfColumnLengthException(bulk, ex);
                                throw;
                            }
                        }
                    }
                
                    internal static DataTable BuildDataTable(IReadOnlyList<{{name}}> items)
                    {
                        DataTable table = new();
                """
            );

            // Add columns to DataTable
            foreach (PropertyMetadata prop in props)
            {
                var clrType = GetClrType(prop.TypeName);
                sb.AppendIndentedLine(2, $"table.Columns.Add(\"{prop.ColumnName}\", typeof({clrType}));");
            }

            sb.AppendEmptyLine();

            var rowArgs = string.Join(", ", props.Select(p => $"item.{p.PropertyName}"));

            sb.Append(
                $$"""
                        for (int i = 0; i < items.Count; i++)
                        {
                            {{name}} item = items[i];
                            table.Rows.Add(
                                {{rowArgs}}
                            );
                        }

                        return table;
                    }

                    private static void ThrowIfColumnLengthException(SqlBulkCopy bulk, SqlException ex)
                    {
                        if (ex.Message.Contains("Received an invalid column length from the bcp client for colid"))
                        {
                            var pattern = @"\d+";
                            Match match = Regex.Match(ex.Message, pattern);
                            var index = Convert.ToInt32(match.Value) - 1;
                            FieldInfo sortedColumnsField = typeof(SqlBulkCopy).GetField("_sortedColumnMappings", BindingFlags.NonPublic | BindingFlags.Instance);
                            var sortedColumns = sortedColumnsField.GetValue(bulk);
                            FieldInfo itemsField = sortedColumns.GetType().GetField("_items", BindingFlags.NonPublic | BindingFlags.Instance);
                            var items = (object[])itemsField.GetValue(sortedColumns);
                            FieldInfo itemdata = items[index].GetType().GetField("_metadata", BindingFlags.NonPublic | BindingFlags.Instance);
                            var metadata = itemdata.GetValue(items[index]);
                            var column = metadata.GetType()
                                .GetField("column", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance)
                                .GetValue(metadata);
                            var length = metadata.GetType()
                                .GetField("length", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance)
                                .GetValue(metadata);
                            throw new DataException($"Column '{column}' contains data with a length greater than {length}", ex);
                        }
                    }
                }
                """
            );

            context.AddSource(
                $"{ns ?? "Global"}.{inserterClassName}.g.cs",
                SourceText.From(sb.ToString(), Encoding.UTF8)
            );
        }
        catch (Exception ex)
        {
            DiagnosticDescriptor descriptor = new(
                id: "SBIGEN001",
                title: "Bulk insert generator error",
                messageFormat: "Bulk insert generator failed: {0}",
                category: "SqlBulkGenerated.Generation",
                defaultSeverity: DiagnosticSeverity.Error,
                isEnabledByDefault: true);

            Diagnostic diagnostic = Diagnostic.Create(descriptor, Location.None, ex.Message);
            context.ReportDiagnostic(diagnostic);
        }
    }

    private static string GetClrType(string typeName)
    {
        return typeName switch
        {
            "string" => "string",
            "int" => "int",
            "long" => "long",
            "short" => "short",
            "byte" => "byte",
            "bool" => "bool",
            "decimal" => "decimal",
            "double" => "double",
            "float" => "float",
            "DateTime" => "DateTime",
            "DateTimeOffset" => "DateTimeOffset",
            "Guid" => "Guid",
            _ => typeName
        };
    }
}
