using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace JK.Common.PolyfillGenerators;

[Generator]
public sealed class IsExternalInitGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("IsExternalInit.g.cs", SourceText.From(IsExternalInitSource.SourceCode, Encoding.UTF8));
        });
    }
}

file static class IsExternalInitSource
{
    public const string SourceCode =
        """
        // <auto-generated/>
        #if !NET5_0_OR_GREATER

        using System.ComponentModel;
        using System.Diagnostics;
        using System.Diagnostics.CodeAnalysis;

        namespace System.Runtime.CompilerServices;

        [DebuggerNonUserCode]
        [ExcludeFromCodeCoverage]
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal static class IsExternalInit
        {
        }

        #endif
        """;
}
