name: 'Common.Abstractions CI'

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - 'src/JK.Common.Abstractions/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'src/JK.Common.Abstractions/**'

permissions:
  contents: read
  pull-requests: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET SDKs
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.x 
          7.x
          8.x
    - name: Build 
      run: dotnet build ./src/JK.Common.Abstractions/JK.Common.Abstractions.csproj -c Release 
