name: 'JK.Common.Data.SQL CI'

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - 'src/JK.Common.Data.Sql/**'
      - 'src/JK.Common.Data.Sql.Tests/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'src/JK.Common.Data.Sql/**'
      - 'src/JK.Common.Data.Sql.Tests/**'

permissions:
  contents: read
  pull-requests: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET SDKs
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          3.1.x 
          6.x 
          7.x
    - name: Build
      run: dotnet build ./src/JK.Common.Data.Sql/JK.Common.Data.Sql.csproj -c Release
    - name: Test
      run: dotnet test ./src/JK.Common.Data.Sql.Tests/JK.Common.Data.Sql.Tests.csproj --verbosity normal
