name: 'Common.Data.SQL CI'

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - 'src/Common.Data.Sql/**'
      - 'src/Common.Data.Sql.Tests/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'src/Common.Data.Sql/**'
      - 'src/Common.Data.Sql.Tests/**'

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    uses: ./.github/workflows/dotnet-parameterized.yml
    with:
      library_project: Common.Data.Sql/JK.Common.Data.Sql.csproj
      test_projects: |
        Common.Data.Sql.Tests/JK.Common.Data.Sql.Tests.csproj
      runs_on: windows-latest
      dotnet_versions: |
        10.x
        9.x
        8.x
