
name: 'Common.EFCore.SqlServer CI'

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - 'src/JK.Common.EntityFrameworkCore.SqlServer/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'src/JK.Common.EntityFrameworkCore.SqlServer/**'

permissions:
  contents: read
  pull-requests: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET SDKs
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.x
    - name: Build
      run: dotnet build ./src/JK.Common.EntityFrameworkCore.SqlServer/JK.Common.EntityFrameworkCore.SqlServer.csproj -c Release
