name: 'Common CI'

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - 'src/Common/**'
      - 'src/Common.Tests/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'src/Common/**'
      - 'src/Common.Tests/**'

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    uses: ./.github/workflows/dotnet-parameterized.yml
    with:
      library_project: Common/JK.Common.csproj
      test_projects: |
        Common.Tests/JK.Common.Tests.csproj
      runs_on: windows-latest
      dotnet_versions: |
        10.x
        9.x
        8.x
