name: 'Common.FluentValidation CI'

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - 'src/Common.FluentValidation/**'
      - 'src/Common.FluentValidation.Tests/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'src/Common.FluentValidation/**'
      - 'src/Common.FluentValidation.Tests/**'

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    uses: ./.github/workflows/dotnet-parameterized.yml
    with:
      library_project: Common.FluentValidation/JK.Common.FluentValidation.csproj
      test_projects: |
        Common.FluentValidation.Tests/JK.Common.FluentValidation.Tests.csproj
      runs_on: ubuntu-latest
      dotnet_versions: |
        10.x
        9.x
        8.x
