# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: 'JK.Common CI'

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  pull-requests: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          3.1.x
          6.x
          7.x
    - name: Restore dependencies
      run: dotnet restore ./src/JK.Common/JK.Common.csproj
    - name: Build
      run: dotnet build ./src/JK.Common/JK.Common.csproj --no-restore
    - name: Test
      run: dotnet test ./src/JK.Common/JK.Common.csproj --no-build --verbosity normal
