name: 'Common CI'

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - 'src/Common/**'
      - 'src/Common.Tests/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'src/Common/**'
      - 'src/Common.Tests/**'

permissions:
  contents: read
  pull-requests: read

env:
  LIBRARY_PROJECT_PATH: ./src/Common/JK.Common.csproj
  TEST_PROJECT_PATH: ./src/Common.Tests/JK.Common.Tests.csproj

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v7
    - name: Setup .NET SDKs
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: |
          10.x
          9.x
          8.x
    - name: Build 
      run: dotnet build $env:LIBRARY_PROJECT_PATH -c Release 
    - name: Format 
      run: dotnet format $env:LIBRARY_PROJECT_PATH --severity error --verify-no-changes
    - name: Test 
      run: dotnet test $env:TEST_PROJECT_PATH --verbosity normal
