name: 'Common.Data.Sql.BulkInsert CI'

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - 'src/Common.Data.Sql.BulkInsert/**'
      - 'src/Common.Data.Sql.BulkInsert.Tests.Integration/**'
      - 'src/Common.Data.Sql.BulkInsert.Tests.Unit/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'src/Common.Data.Sql.BulkInsert/**'
      - 'src/Common.Data.Sql.BulkInsert.Tests.Integration/**'
      - 'src/Common.Data.Sql.BulkInsert.Tests.Unit/**'

permissions:
  contents: read
  pull-requests: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v7
    - name: Setup .NET SDKs
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 10.x
    - name: Build 
      run: dotnet build ./src/Common.FluentValidation/JK.Common.Data.Sql.BulkInsert.csproj -c Release 
    - name: Unit Tests
      run: dotnet test ./src/Common.FluentValidation.Tests/JK.Common.Data.Sql.BulkInsert.Tests.Unit.csproj --verbosity normal
    - name: Integration Tests 
      run: dotnet test ./src/Common.FluentValidation.Tests/JK.Common.Data.Sql.BulkInsert.Tests.Integration.csproj --verbosity normal
