name: 'Common.Data.Sql.BulkInsert CI'

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - 'src/Common.Data.Sql.BulkInsert/**'
      - 'src/Common.Data.Sql.BulkInsert.Tests.Integration/**'
      - 'src/Common.Data.Sql.BulkInsert.Tests.Unit/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'src/Common.Data.Sql.BulkInsert/**'
      - 'src/Common.Data.Sql.BulkInsert.Tests.Integration/**'
      - 'src/Common.Data.Sql.BulkInsert.Tests.Unit/**'

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    uses: ./.github/workflows/dotnet-parameterized.yml
    with:
      library_project: Common.Data.Sql.BulkInsert/JK.Common.Data.Sql.BulkInsert.csproj
      test_projects: |
        Common.Data.Sql.BulkInsert.Tests.Unit/JK.Common.Data.Sql.BulkInsert.Tests.Unit.csproj
        Common.Data.Sql.BulkInsert.Tests.Integration/JK.Common.Data.Sql.BulkInsert.Tests.Integration.csproj
      runs_on: ubuntu-latest
      dotnet_versions: 10.x
