name: 'Common.Polyfills CI'

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - 'src/Common.Polyfills/**'
      - 'src/Common.Polyfills.Tests/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'src/Common.Polyfills/**'
      - 'src/Common.Polyfills.Tests/**'

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    uses: ./.github/workflows/dotnet-parameterized.yml
    with:
      library_project: Common.Polyfills/JK.Common.Polyfills.csproj
      test_projects: |
        Common.Polyfills.Tests/JK.Common.Polyfills.Tests.csproj
      runs_on: ubuntu-latest
      dotnet_versions: 10.x
